### PR TITLE
Fix ability to target constructors with arguments

### PR DESCRIPTION
**Pull request by kelloggm**
Was broken by #325, I think. We should have had a test for this. Should fix the issue @theron-wang observed with na-323 and na-347, which both require a constructor with an argument to be targeted.

### CODE REVIEW

**Review by theron-wang — APPROVED** [review]
The exception is fixed! However, there are now compile-time errors (probably caused by the default values in final fields) but we can do that in another PR.

Here's the stack trace for future reference: 
```
C:\path\to\specimin-evaluation\ISSUES\na-347\output\otr4j\src\main\java\net\java\otr4j\messages\SignatureX.java:23: error: cannot assign a value to final variable longTermPublicKey
        this.longTermPublicKey = requireNonNull(ourLongTermPublicKey);
            ^
C:\path\to\specimin-evaluation\ISSUES\na-347\output\otr4j\src\main\java\net\java\otr4j\messages\SignatureX.java:24: error: cannot assign a value to final variable dhKeyID
        this.dhKeyID = requireNotEquals(0, ourKeyID);
            ^
C:\path\to\specimin-evaluation\ISSUES\na-347\output\otr4j\src\main\java\net\java\otr4j\messages\SignatureX.java:25: error: cannot assign a value to final variable signature
        this.signature = requireLengthExactly(DSA_SIGNATURE_LENGTH_BYTES, signature);
            ^
3 errors

FAILURE: Build failed with an exception.
```

**Comment by kelloggm** [comment]
> The exception is fixed! However, there are now compile-time errors (probably caused by the default values in final fields) but we can do that in another PR.

Great. I will look into that other issue separately, and merge this one now.
